"""Self-contained HTML report generator.

Renders a single-file, dependency-free HTML report (summary counts, threat
findings, timeline) from the pipeline outputs. No external CSS/JS — safe to
open offline or embed in a wiki.
"""

from __future__ import annotations

import html
from typing import Any

_SEV_COLOR = {"critical": "#b00020", "high": "#d84315", "medium": "#f9a825",
              "low": "#2e7d32", "info": "#607d8b"}


def _esc(v: Any) -> str:
    return html.escape("" if v is None else str(v))


def _rows(findings: list[dict]) -> str:
    if not findings:
        return "<tr><td colspan='6'>No threats detected.</td></tr>"
    out = []
    for f in findings:
        color = _SEV_COLOR.get(f.get("severity", "info"), "#607d8b")
        out.append(
            f"<tr><td><span class='pill' style='background:{color}'>"
            f"{_esc(f.get('severity'))}</span></td>"
            f"<td>{int(f.get('confidence', 0) * 100)}%</td>"
            f"<td>{_esc(f.get('type'))}</td>"
            f"<td>{_esc(f.get('technique'))}</td>"
            f"<td>{_esc(f.get('mitre'))}</td>"
            f"<td>{_esc(f.get('process'))} "
            f"{('(pid ' + str(f['pid']) + ')') if f.get('pid') is not None else ''}"
            f"<br><small>{_esc(f.get('evidence'))}</small></td></tr>")
    return "\n".join(out)


def _timeline_rows(timeline: list[dict], limit: int = 200) -> str:
    out = []
    for e in timeline[:limit]:
        color = _SEV_COLOR.get(e.get("severity", "info"), "#607d8b")
        out.append(
            f"<tr><td>{_esc(e.get('@timestamp'))}</td>"
            f"<td><span class='dot' style='background:{color}'></span>"
            f"{_esc(e.get('action'))}</td>"
            f"<td>{_esc(e.get('description'))}</td></tr>")
    return "\n".join(out) or "<tr><td colspan='3'>No timeline events.</td></tr>"


def render(*, dump: str, os_type: str, counts: dict[str, int],
           findings: list[dict], timeline: list[dict], iocs: dict) -> str:
    """Return a complete HTML document string."""
    crit = sum(1 for f in findings if f.get("severity") in ("critical", "high"))
    ioc_lines = "".join(
        f"<li><b>{_esc(k)}</b>: {_esc(', '.join(v[:50]))}</li>"
        for k, v in iocs.items() if v)
    cards = "".join(
        f"<div class='card'><div class='n'>{v}</div><div class='l'>{_esc(k)}</div></div>"
        for k, v in counts.items())
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Mneme report — {_esc(dump)}</title>
<style>
 body{{font:14px/1.5 system-ui,sans-serif;margin:0;background:#0f1115;color:#e6e6e6}}
 header{{padding:24px 32px;background:#161a22;border-bottom:1px solid #262b36}}
 h1{{margin:0;font-size:20px}} .sub{{color:#8a93a2}}
 main{{padding:24px 32px;max-width:1100px}}
 .cards{{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}}
 .card{{background:#161a22;border:1px solid #262b36;border-radius:8px;padding:16px 20px;min-width:120px}}
 .card .n{{font-size:26px;font-weight:700}} .card .l{{color:#8a93a2;font-size:12px}}
 h2{{margin-top:32px;border-bottom:1px solid #262b36;padding-bottom:6px}}
 table{{width:100%;border-collapse:collapse;margin-top:8px}}
 th,td{{text-align:left;padding:8px;border-bottom:1px solid #21262f;vertical-align:top}}
 th{{color:#8a93a2;font-weight:600}}
 .pill{{color:#fff;padding:2px 8px;border-radius:10px;font-size:11px;text-transform:uppercase}}
 .dot{{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}}
 small{{color:#8a93a2}} .tl{{max-height:520px;overflow:auto;display:block}}
</style></head><body>
<header>
 <h1>Mneme — Memory Forensics Report</h1>
 <div class="sub">dump: {_esc(dump)} · os: {_esc(os_type)} · {crit} high/critical findings</div>
</header>
<main>
 <div class="cards">{cards}</div>
 <h2>Threat Detections ({len(findings)})</h2>
 <table><thead><tr><th>Severity</th><th>Conf.</th><th>Type</th><th>Technique</th>
 <th>ATT&amp;CK</th><th>Detail</th></tr></thead><tbody>{_rows(findings)}</tbody></table>
 <h2>Indicators of Compromise</h2>
 <ul>{ioc_lines or '<li>none</li>'}</ul>
 <h2>Timeline ({len(timeline)} events)</h2>
 <div class="tl"><table><thead><tr><th>Time</th><th>Action</th><th>Description</th></tr>
 </thead><tbody>{_timeline_rows(timeline)}</tbody></table></div>
 <p class="sub">Generated by Mneme · <a style="color:#6ab0ff"
   href="https://attack.mitre.org">MITRE ATT&amp;CK</a> techniques referenced.</p>
</main></body></html>"""
